parameters:
    xmlrpc_client.class:        xmlrpc_client
    xmlrpc_client.basic_auth:   ""
    xmlrpc_client.url:          ws.universign.eu/sign/rpc/
    request_manager.class:      Wizacha\UniversignBundle\Request\RequestManager

services:
    xmlrpc_client:
        class:      "%xmlrpc_client.class%"
        arguments:  ["https://%xmlrpc_client.basic_auth%@%xmlrpc_client.url%"]
    request_manager:
        class:      "%request_manager.class%"
        arguments:  ["@xmlrpc_client"]
